help:
- '&7&m-----------------------------------------------------'
- '%centered%&6&lIsland Help'
- '&7&m-----------------------------------------------------'
- '&e/is create &8- &7Create your own island.'
- '&e/is invite &f<playerName> &8- &7Invite a player to your island.'
- '&e/is list &8- &7View all players on your island.'
- '&e/is top &8- &7View the richest Islands.'
- '&e/is sethome &8- &7Set the home to your island.'
- '&e/is home &8- &7Go to your island home.'
- '&e/is leave &8- &7Leave your Island.'
- '&e/is deinvite &f<playerName> &8- &7Revoke invitation to player.'
- '&e/is kick &f<playerName> &8- &7Kick player from your Island.'
- '&e/is mod &f<playerName> &8- &7Set player to mod role in your island.'
- '&e/is coleader &f<playerName> &8- &7Set player to coleader role in your island.'
- '&e/is leader &f<playerName> &8- &7Set player role to leader in your island.'
- '&e/is chat &8- &7Switch to your Island chat.'
- '&e/is warp &8- &7Opens the warp menu.'
- '&e/is setwarp &8- &7Set a warp.'
- '&e/is perms &8- &7Change what players can do in your claims.'
- '&e/is upgrades &8- &7Upgrade your island.'
- '&e/is missions &8- &7Displays your daily Island Missions.'
- '&e/is boosters &8- &7Boost your island using xp.'
- '&e/is version &8- &7Display current Island version.'
- '&7&m-----------------------------------------------------'